defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"
encoding: 'utf-8'
collections:
  pages:
    output: true
    permalink: /:name
  docs:
    output: true
    permalink: /docs/:categories/:name
  join-org:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge